-- Essay Prompts Seed Data
-- Age-appropriate writing prompts for narrative, expository, and persuasive essays

INSERT INTO public.essay_prompts (prompt, type, grade_level, time_limit, rubric) VALUES

-- Grade 6 Narrative Prompts
('Think about a time when you had to be brave. Write a story about what happened, including how you felt before, during, and after the situation. Use descriptive details to help your reader understand your experience.', 
'narrative', 6, 30, 
'{"organization": {"excellent": "Clear beginning, middle, and end with smooth transitions", "good": "Generally well-organized with some transitions", "fair": "Basic organization with few transitions", "poor": "Little organization or unclear structure"}, "content": {"excellent": "Engaging story with rich details and clear personal connection", "good": "Interesting story with good details", "fair": "Basic story with some details", "poor": "Unclear story with few details"}, "language": {"excellent": "Varied sentence structure and precise word choice", "good": "Generally good sentence variety and word choice", "fair": "Some sentence variety with adequate word choice", "poor": "Simple sentences with basic vocabulary"}, "conventions": {"excellent": "Few or no errors in grammar, spelling, punctuation", "good": "Minor errors that don''t interfere with meaning", "fair": "Some errors that occasionally interfere with meaning", "poor": "Many errors that interfere with understanding"}}'),

('Imagine you could spend a day with any person from history. Write a story about your day together. Describe who you chose, what you did, and what you learned from this person.', 
'narrative', 6, 30, 
'{"organization": {"excellent": "Clear beginning, middle, and end with smooth transitions", "good": "Generally well-organized with some transitions", "fair": "Basic organization with few transitions", "poor": "Little organization or unclear structure"}, "content": {"excellent": "Creative story with historical accuracy and meaningful interactions", "good": "Good story with some historical knowledge", "fair": "Basic story with limited historical connection", "poor": "Unclear story with little historical understanding"}, "language": {"excellent": "Varied sentence structure and precise word choice", "good": "Generally good sentence variety and word choice", "fair": "Some sentence variety with adequate word choice", "poor": "Simple sentences with basic vocabulary"}, "conventions": {"excellent": "Few or no errors in grammar, spelling, punctuation", "good": "Minor errors that don''t interfere with meaning", "fair": "Some errors that occasionally interfere with meaning", "poor": "Many errors that interfere with understanding"}}'),

-- Grade 6 Expository Prompts
('Explain how to do something you are good at, such as playing a sport, cooking a dish, or completing a hobby. Write clear step-by-step instructions that would help someone else learn this skill.', 
'expository', 6, 30, 
'{"organization": {"excellent": "Logical sequence with clear transitions between steps", "good": "Generally logical with some transitions", "fair": "Basic sequence with few transitions", "poor": "Unclear sequence or missing steps"}, "content": {"excellent": "Complete, accurate instructions with helpful details", "good": "Good instructions with adequate details", "fair": "Basic instructions with some details", "poor": "Incomplete or unclear instructions"}, "language": {"excellent": "Clear, precise language appropriate for instructions", "good": "Generally clear language", "fair": "Adequate clarity with some confusion", "poor": "Unclear or confusing language"}, "conventions": {"excellent": "Few or no errors in grammar, spelling, punctuation", "good": "Minor errors that don''t interfere with meaning", "fair": "Some errors that occasionally interfere with meaning", "poor": "Many errors that interfere with understanding"}}'),

('Choose an animal that interests you and explain three ways it has adapted to survive in its environment. Use specific examples and details to support your explanation.', 
'expository', 6, 30, 
'{"organization": {"excellent": "Clear introduction, three well-developed body paragraphs, strong conclusion", "good": "Good organization with adequate development", "fair": "Basic organization with some development", "poor": "Poor organization or unclear structure"}, "content": {"excellent": "Accurate information with specific examples and clear explanations", "good": "Good information with some examples", "fair": "Basic information with few examples", "poor": "Inaccurate or insufficient information"}, "language": {"excellent": "Precise scientific vocabulary used correctly", "good": "Good use of appropriate vocabulary", "fair": "Adequate vocabulary with some scientific terms", "poor": "Limited vocabulary or incorrect usage"}, "conventions": {"excellent": "Few or no errors in grammar, spelling, punctuation", "good": "Minor errors that don''t interfere with meaning", "fair": "Some errors that occasionally interfere with meaning", "poor": "Many errors that interfere with understanding"}}'),

-- Grade 6 Persuasive Prompts
('Your school is considering eliminating recess for middle school students to allow more time for academic subjects. Write a letter to your principal explaining whether you agree or disagree with this decision. Use specific reasons and examples to support your position.', 
'persuasive', 6, 30, 
'{"organization": {"excellent": "Clear position with logical argument structure", "good": "Generally clear position with good organization", "fair": "Basic position with some organization", "poor": "Unclear position or poor organization"}, "content": {"excellent": "Strong, specific reasons with relevant examples", "good": "Good reasons with some examples", "fair": "Basic reasons with few examples", "poor": "Weak reasons or no supporting examples"}, "language": {"excellent": "Persuasive language that engages the reader", "good": "Generally persuasive with good word choice", "fair": "Somewhat persuasive with adequate language", "poor": "Not persuasive or inappropriate language"}, "conventions": {"excellent": "Few or no errors in grammar, spelling, punctuation", "good": "Minor errors that don''t interfere with meaning", "fair": "Some errors that occasionally interfere with meaning", "poor": "Many errors that interfere with understanding"}}'),

-- Grade 7 Narrative Prompts
('Write about a time when you had to make a difficult decision. Describe the situation, the choices you had, and explain how you made your decision. Reflect on whether you would make the same choice again and why.', 
'narrative', 7, 30, 
'{"organization": {"excellent": "Sophisticated structure with effective transitions and pacing", "good": "Well-organized with good transitions", "fair": "Adequate organization with some transitions", "poor": "Poor organization or unclear structure"}, "content": {"excellent": "Compelling narrative with deep reflection and insight", "good": "Engaging story with good reflection", "fair": "Adequate story with some reflection", "poor": "Weak story with little reflection"}, "language": {"excellent": "Rich, varied language with strong voice", "good": "Good language variety with clear voice", "fair": "Adequate language with emerging voice", "poor": "Limited language or unclear voice"}, "conventions": {"excellent": "Excellent control of grammar, spelling, punctuation", "good": "Good control with minor errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

('Imagine you wake up one morning and discover you have a superpower. Write a story about your first day with this new ability. Include the challenges and benefits of having this power.', 
'narrative', 7, 30, 
'{"organization": {"excellent": "Creative structure that enhances the story", "good": "Well-organized with clear progression", "fair": "Adequate organization", "poor": "Poor organization or unclear structure"}, "content": {"excellent": "Original, engaging story with well-developed conflict and resolution", "good": "Interesting story with good development", "fair": "Adequate story with some development", "poor": "Weak or unclear story"}, "language": {"excellent": "Vivid, creative language that brings the story to life", "good": "Good descriptive language", "fair": "Adequate language with some description", "poor": "Limited or unclear language"}, "conventions": {"excellent": "Excellent control of grammar, spelling, punctuation", "good": "Good control with minor errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

-- Grade 7 Expository Prompts
('Social media has become a major part of many teenagers'' lives. Explain both the positive and negative effects of social media on young people. Use specific examples to support your points.', 
'expository', 7, 30, 
'{"organization": {"excellent": "Clear, balanced structure addressing both sides effectively", "good": "Well-organized with good balance", "fair": "Adequate organization with some balance", "poor": "Poor organization or heavily one-sided"}, "content": {"excellent": "Insightful analysis with specific, relevant examples", "good": "Good analysis with adequate examples", "fair": "Basic analysis with some examples", "poor": "Weak analysis with few or no examples"}, "language": {"excellent": "Sophisticated vocabulary and varied sentence structure", "good": "Good vocabulary and sentence variety", "fair": "Adequate language skills", "poor": "Limited vocabulary or sentence structure"}, "conventions": {"excellent": "Excellent control of grammar, spelling, punctuation", "good": "Good control with minor errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

('Choose a current environmental issue and explain its causes, effects, and possible solutions. Use facts and examples to make your explanation clear and informative.', 
'expository', 7, 30, 
'{"organization": {"excellent": "Logical structure with smooth transitions between causes, effects, and solutions", "good": "Well-organized with clear sections", "fair": "Adequate organization", "poor": "Poor organization or unclear structure"}, "content": {"excellent": "Accurate, detailed information with strong examples", "good": "Good information with adequate examples", "fair": "Basic information with some examples", "poor": "Inaccurate or insufficient information"}, "language": {"excellent": "Precise, scientific vocabulary used appropriately", "good": "Good use of appropriate vocabulary", "fair": "Adequate vocabulary", "poor": "Limited or incorrect vocabulary"}, "conventions": {"excellent": "Excellent control of grammar, spelling, punctuation", "good": "Good control with minor errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

-- Grade 7 Persuasive Prompts
('Many schools are considering requiring students to wear uniforms. Write an essay arguing for or against school uniforms. Use logical reasons and specific examples to convince your reader.', 
'persuasive', 7, 30, 
'{"organization": {"excellent": "Compelling argument structure with effective counterargument", "good": "Clear argument with good organization", "fair": "Adequate argument structure", "poor": "Weak or unclear argument"}, "content": {"excellent": "Strong, logical reasons with convincing evidence", "good": "Good reasons with adequate support", "fair": "Basic reasons with some support", "poor": "Weak reasons or insufficient support"}, "language": {"excellent": "Persuasive, engaging language that connects with audience", "good": "Generally persuasive language", "fair": "Somewhat persuasive language", "poor": "Not persuasive or inappropriate tone"}, "conventions": {"excellent": "Excellent control of grammar, spelling, punctuation", "good": "Good control with minor errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

-- Grade 8 Narrative Prompts
('Write about a moment when you realized something important about yourself or the world around you. Describe not only what happened, but also how this realization changed your perspective or behavior.', 
'narrative', 8, 30, 
'{"organization": {"excellent": "Sophisticated narrative structure with effective use of literary techniques", "good": "Well-crafted organization with good pacing", "fair": "Adequate organization", "poor": "Poor organization or unclear structure"}, "content": {"excellent": "Profound insight with mature reflection and universal themes", "good": "Good insight with thoughtful reflection", "fair": "Adequate insight with some reflection", "poor": "Limited insight or shallow reflection"}, "language": {"excellent": "Sophisticated, nuanced language with strong personal voice", "good": "Mature language with clear voice", "fair": "Adequate language with emerging voice", "poor": "Immature language or unclear voice"}, "conventions": {"excellent": "Masterful control of grammar, spelling, punctuation", "good": "Strong control with few errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

('Think about a tradition that is important to your family or culture. Write a story that shows why this tradition matters, including specific details about how it is celebrated and what it means to you.', 
'narrative', 8, 30, 
'{"organization": {"excellent": "Engaging structure that effectively showcases the tradition", "good": "Well-organized with clear focus", "fair": "Adequate organization", "poor": "Poor organization or unclear focus"}, "content": {"excellent": "Rich cultural details with deep personal meaning", "good": "Good cultural details with personal connection", "fair": "Some cultural details with basic connection", "poor": "Few details or weak connection"}, "language": {"excellent": "Vivid, culturally authentic language", "good": "Good descriptive language", "fair": "Adequate descriptive language", "poor": "Limited or unclear language"}, "conventions": {"excellent": "Masterful control of grammar, spelling, punctuation", "good": "Strong control with few errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

-- Grade 8 Expository Prompts
('Technology has dramatically changed how people communicate. Compare and contrast communication methods from 50 years ago with those used today. Analyze both the advantages and disadvantages of these changes.', 
'expository', 8, 30, 
'{"organization": {"excellent": "Sophisticated compare/contrast structure with insightful analysis", "good": "Clear comparison with good analysis", "fair": "Adequate comparison with some analysis", "poor": "Weak comparison or little analysis"}, "content": {"excellent": "Thorough, accurate information with mature insights", "good": "Good information with solid insights", "fair": "Adequate information with basic insights", "poor": "Limited or inaccurate information"}, "language": {"excellent": "Sophisticated vocabulary and complex sentence structures", "good": "Good vocabulary and sentence variety", "fair": "Adequate language skills", "poor": "Limited vocabulary or sentence structure"}, "conventions": {"excellent": "Masterful control of grammar, spelling, punctuation", "good": "Strong control with few errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

('Explain the concept of leadership and describe the qualities that make someone an effective leader. Use examples from history, current events, or personal experience to support your explanation.', 
'expository', 8, 30, 
'{"organization": {"excellent": "Clear definition followed by well-developed examples", "good": "Good organization with adequate examples", "fair": "Basic organization with some examples", "poor": "Poor organization or few examples"}, "content": {"excellent": "Insightful understanding of leadership with compelling examples", "good": "Good understanding with relevant examples", "fair": "Basic understanding with adequate examples", "poor": "Limited understanding or weak examples"}, "language": {"excellent": "Sophisticated vocabulary demonstrating mature understanding", "good": "Good vocabulary and clear expression", "fair": "Adequate vocabulary and expression", "poor": "Limited vocabulary or unclear expression"}, "conventions": {"excellent": "Masterful control of grammar, spelling, punctuation", "good": "Strong control with few errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

-- Grade 8 Persuasive Prompts
('Some people believe that students should have more control over their education, including choosing their own classes and setting their own schedules. Others believe that adults should make these decisions for students. Take a position on this issue and defend it with logical arguments and evidence.', 
'persuasive', 8, 30, 
'{"organization": {"excellent": "Sophisticated argument with effective counterargument and rebuttal", "good": "Strong argument with good organization", "fair": "Adequate argument structure", "poor": "Weak or unclear argument"}, "content": {"excellent": "Compelling, logical arguments with strong evidence", "good": "Good arguments with adequate evidence", "fair": "Basic arguments with some evidence", "poor": "Weak arguments or insufficient evidence"}, "language": {"excellent": "Persuasive, mature language that engages and convinces", "good": "Generally persuasive with good word choice", "fair": "Somewhat persuasive language", "poor": "Not persuasive or inappropriate tone"}, "conventions": {"excellent": "Masterful control of grammar, spelling, punctuation", "good": "Strong control with few errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}'),

('Climate change is one of the most pressing issues facing our world today. Write a persuasive essay arguing for specific actions that individuals, communities, or governments should take to address this challenge.', 
'persuasive', 8, 30, 
'{"organization": {"excellent": "Compelling structure with clear call to action", "good": "Strong organization with good flow", "fair": "Adequate organization", "poor": "Poor organization or unclear structure"}, "content": {"excellent": "Well-researched, specific solutions with strong reasoning", "good": "Good solutions with adequate reasoning", "fair": "Basic solutions with some reasoning", "poor": "Vague solutions or weak reasoning"}, "language": {"excellent": "Powerful, urgent language appropriate for the topic", "good": "Effective persuasive language", "fair": "Somewhat persuasive language", "poor": "Not persuasive or inappropriate tone"}, "conventions": {"excellent": "Masterful control of grammar, spelling, punctuation", "good": "Strong control with few errors", "fair": "Adequate control with some errors", "poor": "Poor control with many errors"}}');