name: Deploy to Production

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run frontend tests
      run: cd frontend && npm run test:coverage
    
    - name: Run backend tests
      run: cd backend && npm run test:coverage
    
    - name: Run E2E tests
      run: cd frontend && npm run test:e2e

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: npm audit --audit-level high
    
    - name: Check for vulnerabilities
      run: |
        cd frontend && npm audit --audit-level high
        cd ../backend && npm audit --audit-level high

  deploy:
    needs: [test, security-scan]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  post-deploy:
    needs: [deploy]
    runs-on: ubuntu-latest
    
    steps:
    - name: Run smoke tests
      run: |
        # Wait for deployment to be ready
        sleep 30
        
        # Test application health
        curl -f https://babysteps-frontend.vercel.app/api/health || exit 1
    
    - name: Notify deployment success
      run: echo "✅ Production deployment successful"